server:
  port: 8080
  
security:
  oauth2:
    client:
      client-id: microclient
      client-secret: secret
    resource:
       #token-info-uri: http://localhost:8081/auth/oauth/check_token
       #user-info-uri: http://localhost:8081/auth/userinfo
       jwt:
        key-uri: http://localhost:8081/auth/oauth/token_key
